apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jxie
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gslo-tenant/rhtap-demo-app/hacbs-test-project-jxie@sha256:68be6c83f26226b2ba84f1b40b3ef239d3aa397ccafbdf0c6094decd38260e64
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
