apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jxie
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jxie
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jxie
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jxie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jxie
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gslo-tenant/rhtap-demo-app/hacbs-test-project-jxie@sha256:68be6c83f26226b2ba84f1b40b3ef239d3aa397ccafbdf0c6094decd38260e64
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
